[package]
name = "rustlib"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]
name = "rustlib"

[dependencies]
log = "0.4"
image = "0.25.2"
imageproc = "0.25.0"
chrono = "0.4"
anyhow = "1.0"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13"
jni = "0.21.1"
